/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import * as THREE from 'three'
import { useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { RootState, useFrame } from '@react-three/fiber'
// import { easing } from 'maath'

type GLTFResult = GLTF & {
	nodes: {
		['React-Logo_Material002_0']: THREE.Mesh
	}
	materials: {
		['Material.002']: THREE.MeshStandardMaterial
	}
}

export default function Model(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF('/react_logo.glb') as GLTFResult
	// materials['Material.002'].emissiveIntensity = 5
	materials['Material.002'].toneMapped = false

	const [changeGlow, setChangeGlow] = useState(false)

	const runReactModelClickAnimation = (state: any) => {
		if (changeGlow) {
			materials['Material.002'].emissiveIntensity =
				Math.sin(10 * state.clock.elapsedTime) * 2 + 6
		} else {
			materials['Material.002'].emissiveIntensity =
				Math.sin(2 * state.clock.elapsedTime) * 2 + 6
		}
	}

	useFrame((state: RootState) => {
		runReactModelClickAnimation(state)
		// console.log(Math.sin(delta) * 1000)
	})

	return (
		<group
			{...props}
			dispose={null}
			onPointerEnter={() => setChangeGlow(true)}
			onPointerLeave={() => setChangeGlow(false)}
		>
			<group scale={0.01}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes['React-Logo_Material002_0'].geometry}
					material={materials['Material.002']}
					position={[1, 7.935, 18.102]}
					rotation={[0, 0, -Math.PI / 2]}
					scale={[39.166, 39.166, 52.734]}
				/>
				<mesh
					onPointerEnter={() => setChangeGlow(true)}
					onPointerLeave={() => setChangeGlow(false)}
					scale={[39.166, 39.166, 52.734]}
				>
					<boxGeometry args={[10, 10, 10]} />
					<meshBasicMaterial
						transparent
						opacity={0}
					/>
				</mesh>
			</group>
		</group>
	)
}

useGLTF.preload('/react_logo.glb')
